version: '3.3'

services:
  db: 
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "C:\\Users\\seven\\OneDrive\\Documentos\\Projetos\\CURSOS\\Docker\\curso_docker_eu\\5_compose\\6_bind_mount_compose\\flask:/app" # O código desse diretorório aqui reflete (:) em /app (Workdir)
    networks:
      - dockercompose

networks:
  dockercompose: